/**
 * Per-service Open Graph images (SEO-008). Generated by `npm run og:generate`
 * into public/images/og/. Dutch text only: nl is the primary market.
 */
export const OG_IMAGE_SIZE = { width: 1200, height: 630 } as const

/** Fallback for every page without its own image (resized site hero). */
export const OG_DEFAULT_IMAGE = '/images/og/default.jpg'

/** Service page slug → OG image path; text comes from `detail.<detailKey>` in nl.json. */
export const SERVICE_OG_IMAGES = {
  'software-development': { detailKey: 'software', image: '/images/og/software-development.png' },
  'cms-websites': { detailKey: 'cms', image: '/images/og/cms-websites.png' },
  'it-consulting': { detailKey: 'consulting', image: '/images/og/it-consulting.png' },
  'it-support': { detailKey: 'support', image: '/images/og/it-support.png' },
  'digital-strategy': { detailKey: 'strategy', image: '/images/og/digital-strategy.png' },
} as const

export type ServiceOgSlug = keyof typeof SERVICE_OG_IMAGES
